import React, { useEffect, useState } from 'react';
import { 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  Tooltip, 
  Legend, 
  ResponsiveContainer, 
  PieChart, 
  Pie, 
  Cell 
} from 'recharts';
import { 
  FileText, 
  TrendingUp, 
  CheckCircle2, 
  Clock, 
  Video, 
  Kanban,
  AlertCircle,
  Download
} from 'lucide-react';
import { api, AnalyticsData } from '../services/api';
import { motion } from 'framer-motion';

export const Analytics: React.FC = () => {
  const [data, setData] = useState<AnalyticsData | null>(null);
  const [loading, setLoading] = useState(true);

  const loadAnalytics = async () => {
    try {
      setLoading(true);
      const res = await api.getAnalytics();
      setData(res);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAnalytics();
  }, []);

  const COLORS = ['#8a8886', '#0078d4', '#8660a9', '#107c41']; // To Do, In Progress, Testing, Completed
  const PRIORITY_COLORS = ['#d83b01', '#ffb900', '#0078d4']; // High, Medium, Low

  const handlePrintPDF = () => {
    window.print();
  };

  if (loading || !data) {
    return (
      <div className="min-h-[60vh] flex flex-col justify-center items-center text-slate-400">
        <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-ms-blue mb-4"></div>
        <p className="text-xs">Loading analytics data streams...</p>
      </div>
    );
  }

  const { metrics, charts } = data;

  return (
    <div className="p-8 space-y-8 max-w-7xl mx-auto printable-area">
      
      {/* Printable Heading (Only visible in Print CSS) */}
      <div className="hidden print:block text-center border-b pb-6 space-y-2">
        <h1 className="text-2xl font-bold text-slate-900">Sprint & Meeting Automation Executive Summary</h1>
        <p className="text-xs text-slate-500">Report Generated: {new Date().toLocaleDateString()} | Platform Status: Verified</p>
      </div>

      {/* Header and Download controls */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 print:hidden">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-slate-100">Project Performance Insights</h1>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">Aggregated task metrics and workload analysis charts generated by Microsoft Copilot.</p>
        </div>
        
        <button
          onClick={handlePrintPDF}
          className="w-full md:w-auto px-4 py-2 bg-ms-blue hover:bg-ms-blue-hover text-white rounded-lg text-xs font-bold flex items-center justify-center gap-2 shadow-md shadow-ms-blue/20 cursor-pointer active:scale-95"
        >
          <FileText className="w-4 h-4" />
          Download Summary PDF
        </button>
      </div>

      {/* Analytics Cards Grid */}
      <div className="grid grid-cols-2 lg:grid-cols-6 gap-4">
        {[
          { label: 'Total Meetings', value: metrics.totalMeetings, icon: Video, color: 'text-purple-600 bg-purple-50 dark:bg-purple-950/20' },
          { label: 'Tasks Created', value: metrics.tasksGenerated, icon: Kanban, color: 'text-blue-600 bg-blue-50 dark:bg-blue-950/20' },
          { label: 'Tasks Completed', value: metrics.completedTasks, icon: CheckCircle2, color: 'text-emerald-600 bg-emerald-50 dark:bg-emerald-950/20' },
          { label: 'Pending Tasks', value: metrics.pendingTasks, icon: Clock, color: 'text-amber-600 bg-amber-50 dark:bg-amber-950/20' },
          { label: 'Avg Completion', value: metrics.averageCompletionTime, icon: TrendingUp, color: 'text-indigo-600 bg-indigo-50 dark:bg-indigo-950/20' },
          { label: 'High Priority', value: metrics.highPriorityTasks, icon: AlertCircle, color: 'text-rose-600 bg-rose-50 dark:bg-rose-950/20' },
        ].map((item, idx) => {
          const Icon = item.icon;
          return (
            <div key={idx} className="glass-panel p-4 rounded-xl flex flex-col justify-between h-[110px] shadow-sm">
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wide leading-tight">{item.label}</span>
              <div className="flex justify-between items-end mt-2">
                <span className="text-2xl font-extrabold text-slate-900 dark:text-slate-100">{item.value}</span>
                <div className={`p-2 rounded-lg ${item.color}`}>
                  <Icon className="w-4 h-4" />
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Charts Panels */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Left: Task Status Distribution (Pie Chart) */}
        <div className="glass-panel p-6 rounded-xl space-y-6 flex flex-col">
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Task Status Distribution</h3>
          <div className="flex-1 min-h-[220px] flex items-center justify-center">
            <ResponsiveContainer width="100%" height={220}>
              <PieChart>
                <Pie
                  data={charts.statusData}
                  cx="50%"
                  cy="50%"
                  innerRadius={60}
                  outerRadius={80}
                  paddingAngle={5}
                  dataKey="value"
                >
                  {charts.statusData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip />
              </PieChart>
            </ResponsiveContainer>
          </div>
          
          {/* Status Legends */}
          <div className="grid grid-cols-2 gap-2 text-[10px] font-bold text-slate-500 pt-2">
            {charts.statusData.map((d, index) => (
              <div key={d.name} className="flex items-center gap-1.5">
                <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: COLORS[index] }} />
                <span>{d.name}: {d.value}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Middle: Workload per Assignee (Stacked Bar Chart) */}
        <div className="glass-panel p-6 rounded-xl space-y-6 lg:col-span-2 flex flex-col">
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Team Workload Distribution</h3>
          <div className="flex-1 min-h-[220px]">
            <ResponsiveContainer width="100%" height={240}>
              <BarChart
                data={charts.assigneeData}
                margin={{ top: 10, right: 10, left: -20, bottom: 0 }}
              >
                <XAxis dataKey="name" stroke="#888888" fontSize={11} tickLine={false} axisLine={false} />
                <YAxis stroke="#888888" fontSize={11} tickLine={false} axisLine={false} />
                <Tooltip />
                <Legend iconSize={10} wrapperStyle={{ fontSize: 10, fontWeight: 'bold' }} />
                <Bar dataKey="To Do" stackId="a" fill="#8a8886" radius={[0, 0, 0, 0]} />
                <Bar dataKey="In Progress" stackId="a" fill="#0078d4" radius={[0, 0, 0, 0]} />
                <Bar dataKey="Testing" stackId="a" fill="#8660a9" radius={[0, 0, 0, 0]} />
                <Bar dataKey="Completed" stackId="a" fill="#107c41" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Priority breakdown chart */}
        <div className="glass-panel p-6 rounded-xl space-y-6 flex flex-col">
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Priority Distribution</h3>
          <div className="flex-1 min-h-[220px] flex items-center justify-center">
            <ResponsiveContainer width="100%" height={220}>
              <PieChart>
                <Pie
                  data={charts.priorityData}
                  cx="50%"
                  cy="50%"
                  outerRadius={75}
                  dataKey="value"
                  label={({ name, percent }) => `${name} ${percent ? (percent * 100).toFixed(0) : 0}%`}
                  labelLine={false}
                >
                  {charts.priorityData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={PRIORITY_COLORS[index % PRIORITY_COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Timeline Sprint Overview mockup */}
        <div className="glass-panel p-6 rounded-xl space-y-4 lg:col-span-2">
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Sprint Automation Timeline</h3>
          
          <div className="relative border-l border-slate-200 dark:border-slate-800 ml-4 py-2 space-y-6">
            {[
              { time: 'Day 1', title: 'Setup & Kickoff', desc: 'Created CI/CD pipeline JIRA-103. Copilot initialized repository hooks.', active: true },
              { time: 'Day 3', title: 'Authentication gateway integration', desc: 'Authentication middleware integrated JIRA-104. Slack alerting active.', active: true },
              { time: 'Day 5', title: 'Sprint Mid-Sync', desc: 'Teams meeting concluded, parsed transcript, synchronized Login API and design specs.', active: true },
              { time: 'Day 8 (Current)', title: 'QA & Sprint Wrap', desc: 'Security testing begins, dashboard layouts finalizing.', active: false }
            ].map((node, i) => (
              <div key={i} className="relative pl-6">
                {/* Timeline node node indicator */}
                <div className={`absolute -left-[6px] top-1 w-3 h-3 rounded-full border-2 bg-white dark:bg-slate-900 transition-colors ${
                  node.active 
                    ? 'border-ms-blue dark:border-blue-500 bg-ms-blue' 
                    : 'border-slate-300 dark:border-slate-700'
                }`} />
                <div className="space-y-0.5">
                  <span className="text-[9px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wide">{node.time}</span>
                  <h4 className="text-xs font-bold text-slate-800 dark:text-slate-200">{node.title}</h4>
                  <p className="text-xs text-slate-500 dark:text-slate-400">{node.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Styled Printable Stylesheets (Hide layout components on print, and reformat pages for report output) */}
      <style>{`
        @media print {
          /* Hide workspace sidebars and headers */
          aside, header, button, .print\\:hidden {
            display: none !important;
          }
          /* Expand workspace layout */
          body, .printable-area {
            background: white !important;
            color: black !important;
            width: 100% !important;
            margin: 0 !important;
            padding: 20px !important;
          }
          .glass-panel, .glass-card {
            border: 1px solid #ddd !important;
            box-shadow: none !important;
            background: white !important;
            backdrop-filter: none !important;
          }
        }
      `}</style>

    </div>
  );
};
export default Analytics;
