import express from 'express';
import cors from 'cors';
import { 
  getDatabase, 
  saveDatabase, 
  resetDatabase, 
  Meeting, 
  JiraTicket, 
  SlackMessage, 
  TeamsActivity 
} from './db';
import { analyzeTranscript } from './aiService';

const app = express();
const PORT = process.env.PORT || 5001;

app.use(cors());
app.use(express.json());

// Helper to simulate latency
const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

// Middleware for simulated network latency
app.use(async (req, res, next) => {
  const db = getDatabase();
  const latency = db.settings?.latencyMs || 0;
  if (latency > 0) {
    await delay(latency);
  }
  next();
});

// ==========================================
// MEETING ENDPOINTS
// ==========================================

// Get all meetings
app.get('/api/meetings', (req, res) => {
  const db = getDatabase();
  res.json(db.meetings);
});

// Create a new meeting (simulating active meeting starting)
app.post('/api/meetings', (req, res) => {
  const db = getDatabase();
  const { title, participants } = req.body;
  
  const newMeeting: Meeting = {
    id: `meet-${Date.now()}`,
    title: title || 'Quick Sync Meeting',
    participants: participants || ['John', 'Sarah', 'Mike'],
    status: 'running',
    transcript: [],
    duration: 0,
    analysis: null,
    createdAt: new Date().toISOString()
  };
  
  db.meetings.unshift(newMeeting);
  saveDatabase(db);
  res.status(201).json(newMeeting);
});

// Add transcript line to active meeting
app.post('/api/meetings/:id/transcript', (req, res) => {
  const db = getDatabase();
  const { id } = req.params;
  const { speaker, text, timestamp } = req.body;

  const meeting = db.meetings.find(m => m.id === id);
  if (!meeting) {
    return res.status(404).json({ error: 'Meeting not found' });
  }

  if (meeting.status !== 'running') {
    return res.status(400).json({ error: 'Meeting is already ended' });
  }

  meeting.transcript.push({
    speaker,
    text,
    timestamp: timestamp || new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
  });

  saveDatabase(db);
  res.json(meeting);
});

// End active meeting
app.post('/api/meetings/:id/end', (req, res) => {
  const db = getDatabase();
  const { id } = req.params;
  const { duration } = req.body;

  const meeting = db.meetings.find(m => m.id === id);
  if (!meeting) {
    return res.status(404).json({ error: 'Meeting not found' });
  }

  meeting.status = 'ended';
  meeting.duration = duration || Math.floor(Math.random() * 20) + 15; // default 15-35 mins

  // Push activity notification
  db.teamsActivity.unshift({
    id: `act-${Date.now()}`,
    title: 'Meeting Ended',
    description: `Teams meeting "${meeting.title}" completed. Recording and transcript saved.`,
    type: 'meeting_ended',
    timestamp: 'Just now',
    user: 'Teams'
  });

  saveDatabase(db);
  res.json(meeting);
});

// Trigger Copilot analysis
app.post('/api/meetings/:id/analyze', (req, res) => {
  const db = getDatabase();
  const { id } = req.params;

  const meeting = db.meetings.find(m => m.id === id);
  if (!meeting) {
    return res.status(404).json({ error: 'Meeting not found' });
  }

  if (meeting.status !== 'ended') {
    return res.status(400).json({ error: 'Cannot analyze a running meeting. End it first.' });
  }

  // Generate simulated analysis using the aiService Heuristics
  meeting.analysis = analyzeTranscript(meeting.transcript);
  
  saveDatabase(db);
  res.json(meeting);
});

// Commit analyzed tasks into Jira, Slack, Teams
app.post('/api/meetings/:id/sync', (req, res) => {
  const db = getDatabase();
  const { id } = req.params;

  const meeting = db.meetings.find(m => m.id === id);
  if (!meeting) {
    return res.status(404).json({ error: 'Meeting not found' });
  }

  if (!meeting.analysis) {
    return res.status(400).json({ error: 'No Copilot analysis found to sync. Run analysis first.' });
  }

  const { tasks } = meeting.analysis;
  if (tasks.length === 0) {
    return res.json({ message: 'No tasks found to sync.' });
  }

  const createdTickets: JiraTicket[] = [];
  const startId = 100 + db.tickets.length + 1;

  tasks.forEach((task, index) => {
    const ticketId = `JIRA-${startId + index}`;
    
    // Create Jira ticket
    const newTicket: JiraTicket = {
      id: ticketId,
      title: task.title,
      description: `Task automatically generated by Microsoft Copilot from Teams Meeting "${meeting.title}".\nDue by: ${task.dueDate}.`,
      assignee: task.assignee,
      sprint: 'Sprint 1',
      priority: task.priority,
      dueDate: task.dueDate,
      status: task.status,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };

    db.tickets.unshift(newTicket);
    createdTickets.push(newTicket);

    // Create Teams Activity Feed item
    db.teamsActivity.unshift({
      id: `act-sync-${Date.now()}-${index}`,
      title: 'New Jira Ticket Created',
      description: `Copilot created ${ticketId} for ${task.assignee}: ${task.title}`,
      type: 'sprint_update',
      timestamp: 'Just now',
      user: 'Copilot'
    });
  });

  // Create Slack channel notification message
  const slackTextLines = [
    `🤖 **Copilot**`,
    `${tasks.length} Jira tasks created successfully for **${meeting.title}**:`
  ];
  tasks.forEach((task, i) => {
    const tId = createdTickets[i]?.id || 'JIRA-XXX';
    slackTextLines.push(`• **${task.assignee}** → ${task.title} [${tId}] (Due ${task.dueDate}, Priority: ${task.priority})`);
  });

  db.slackMessages.push({
    id: `slack-sync-${Date.now()}`,
    sender: '🤖 Copilot',
    text: slackTextLines.join('\n'),
    timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    channel: '#sprint-automation',
    isBot: true
  });

  saveDatabase(db);
  res.json({
    message: `${tasks.length} tasks synced successfully.`,
    tickets: createdTickets
  });
});

// ==========================================
// JIRA TICKET ENDPOINTS
// ==========================================

// Get all Jira tickets
app.get('/api/jira/tickets', (req, res) => {
  const db = getDatabase();
  res.json(db.tickets);
});

// Create a Jira ticket manually
app.post('/api/jira/tickets', (req, res) => {
  const db = getDatabase();
  const { title, description, assignee, priority, dueDate, status } = req.body;

  const nextNum = 100 + db.tickets.length + 1;
  const newTicket: JiraTicket = {
    id: `JIRA-${nextNum}`,
    title: title || 'New Integration Task',
    description: description || 'Manually created task.',
    assignee: assignee || 'John',
    sprint: 'Sprint 1',
    priority: priority || 'Medium',
    dueDate: dueDate || 'Friday',
    status: status || 'To Do',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  };

  db.tickets.unshift(newTicket);
  saveDatabase(db);
  res.status(201).json(newTicket);
});

// Update a Jira ticket status
app.patch('/api/jira/tickets/:id', (req, res) => {
  const db = getDatabase();
  const { id } = req.params;
  const { status } = req.body;

  const ticket = db.tickets.find(t => t.id === id);
  if (!ticket) {
    return res.status(404).json({ error: 'Ticket not found' });
  }

  const oldStatus = ticket.status;
  if (oldStatus === status) {
    return res.json(ticket);
  }

  ticket.status = status;
  ticket.updatedAt = new Date().toISOString();

  // Create notifications depending on status transitions
  let statusEmoji = '🔄';
  let activityType: TeamsActivity['type'] = 'sprint_update';
  
  if (status === 'In Progress') {
    statusEmoji = '🚀';
    activityType = 'task_start';
  } else if (status === 'Testing') {
    statusEmoji = '🔬';
    activityType = 'task_testing';
  } else if (status === 'Completed') {
    statusEmoji = '✅';
    activityType = 'task_complete';
  }

  // 1. Post to Slack
  db.slackMessages.push({
    id: `slack-update-${Date.now()}`,
    sender: '🤖 Copilot',
    text: `${statusEmoji} Jira ticket **${ticket.id}** (${ticket.title}) was moved to **${status}** by **${ticket.assignee}**.`,
    timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    channel: '#sprint-automation',
    isBot: true
  });

  // 2. Post to Teams Activity Feed
  db.teamsActivity.unshift({
    id: `teams-update-${Date.now()}`,
    title: `Jira Status Updated`,
    description: `${ticket.assignee} changed ${ticket.id} status to ${status}.`,
    type: activityType,
    timestamp: 'Just now',
    user: ticket.assignee
  });

  saveDatabase(db);
  res.json(ticket);
});

// ==========================================
// SLACK MESSAGES ENDPOINTS
// ==========================================

// Get Slack messages
app.get('/api/slack/messages', (req, res) => {
  const db = getDatabase();
  res.json(db.slackMessages);
});

// Send Slack message manually
app.post('/api/slack/messages', (req, res) => {
  const db = getDatabase();
  const { sender, text, channel } = req.body;

  const newMessage: SlackMessage = {
    id: `slack-msg-${Date.now()}`,
    sender: sender || 'User',
    text: text || '',
    timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    channel: channel || '#sprint-automation',
    isBot: false
  };

  db.slackMessages.push(newMessage);
  saveDatabase(db);
  res.status(201).json(newMessage);
});

// ==========================================
// TEAMS ACTIVITY ENDPOINTS
// ==========================================

// Get Teams Activity Feed
app.get('/api/teams/activity', (req, res) => {
  const db = getDatabase();
  res.json(db.teamsActivity);
});

// ==========================================
// ANALYTICS ENDPOINTS
// ==========================================

// Get statistics and chart aggregates
app.get('/api/analytics', (req, res) => {
  const db = getDatabase();
  const tickets = db.tickets;
  const meetings = db.meetings;

  const totalMeetings = meetings.length;
  const tasksGenerated = tickets.length;
  const completedTasks = tickets.filter(t => t.status === 'Completed').length;
  const pendingTasks = tickets.filter(t => t.status !== 'Completed').length;
  
  // Calculate average completion time (mocked, but relative to completed tickets)
  const averageCompletionTime = completedTasks > 0 ? '1.8 Days' : 'N/A';
  
  const highPriorityTasks = tickets.filter(t => t.priority === 'High').length;

  // 1. Task Status Distribution
  const statusCounts = {
    'To Do': tickets.filter(t => t.status === 'To Do').length,
    'In Progress': tickets.filter(t => t.status === 'In Progress').length,
    'Testing': tickets.filter(t => t.status === 'Testing').length,
    'Completed': tickets.filter(t => t.status === 'Completed').length
  };

  // Convert for frontend chart representation
  const statusData = Object.entries(statusCounts).map(([name, value]) => ({ name, value }));

  // 2. Assignee Workload
  const assignees = Array.from(new Set(tickets.map(t => t.assignee)));
  const assigneeData = assignees.map(name => {
    const userTickets = tickets.filter(t => t.assignee === name);
    return {
      name,
      'To Do': userTickets.filter(t => t.status === 'To Do').length,
      'In Progress': userTickets.filter(t => t.status === 'In Progress').length,
      'Testing': userTickets.filter(t => t.status === 'Testing').length,
      'Completed': userTickets.filter(t => t.status === 'Completed').length,
      total: userTickets.length
    };
  });

  // 3. Priority Distribution
  const priorityCounts = {
    'High': tickets.filter(t => t.priority === 'High').length,
    'Medium': tickets.filter(t => t.priority === 'Medium').length,
    'Low': tickets.filter(t => t.priority === 'Low').length
  };
  const priorityData = Object.entries(priorityCounts).map(([name, value]) => ({ name, value }));

  res.json({
    metrics: {
      totalMeetings,
      tasksGenerated,
      completedTasks,
      pendingTasks,
      averageCompletionTime,
      highPriorityTasks
    },
    charts: {
      statusData,
      assigneeData,
      priorityData
    }
  });
});

// ==========================================
// SETTINGS ENDPOINTS
// ==========================================

// Reset the database
app.post('/api/settings/reset', (req, res) => {
  const resetDb = resetDatabase();
  res.json({ message: 'Database reset successfully', db: resetDb });
});

// Update settings
app.patch('/api/settings', (req, res) => {
  const db = getDatabase();
  const { latencyMs } = req.body;

  if (typeof latencyMs === 'number') {
    db.settings = { ...db.settings, latencyMs };
    saveDatabase(db);
  }

  res.json(db.settings);
});

// Start Server
app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});
